version: "3"
services:
  wordshub:
    image: kramat/wordshub
    env_file:
      - ../.env
    environment:
      WORDSHUB_DB_HOST: db
    depends_on:
      - db
    ports:
      - ${WORDSHUB_PORT}:${WORDSHUB_PORT}
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${WORDSHUB_DB_USER}
      POSTGRES_PASSWORD: ${WORDSHUB_DB_PASSWORD}
      POSTGRES_DB: ${WORDSHUB_DB_NAME}
    ports:
      - ${WORDSHUB_DB_PORT}:${WORDSHUB_DB_PORT}
    volumes:
      - postgresql:/var/lib/postgresql/wordshub
      - postgresql_data:/var/lib/postgresql/wordshub/data
volumes:
  postgresql: {}
  postgresql_data: {}
